import type { Metadata } from "next";
import "./globals.scss";
import ThemeToggle from "../components/ThemeToggle";

export const metadata: Metadata = {
  title: "Ask",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <ThemeToggle />
        {children}
      </body>
    </html>
  );
}
